sudo: false
language: python
python:
  - "2.7"
env:
- PYBOSSA_SETTINGS='../settings_test.py' PYBOSSA_REDIS_CACHE_DISABLED='1' SWIG=swig-2.0.11
services:
- redis-server
addons:
  postgresql: "9.3"
before_install:
# Install swig by compiling (sudo not allowed)
- wget http://prdownloads.sourceforge.net/swig/$SWIG.tar.gz
- tar -xvf $SWIG.tar.gz
- pushd $SWIG && mkdir vendor
- ./configure --prefix=`pwd`/vendor
- make -j 5 && make install
- popd
- export PATH=${PATH}:`pwd`/$SWIG/vendor/bin
install:
- git clone --recursive https://github.com/PyBossa/pybossa.git
- cd pybossa/
- git checkout issue-plugins
- pip install -r requirements.txt
- cd ..
- pip install -U pip
- pip install --editable pybossa
- cp -r random_scheduler/ pybossa/pybossa/plugins/
before_script:
- redis-server --version
- redis-server pybossa/contrib/redis/sentinel.conf --sentinel
- pip --version
- psql -c "create user rtester with createdb login password 'rtester'" -U postgres
- psql -c "create database pybossa_test owner rtester encoding 'UTF-8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;" -U postgres
script: nosetests test/ pybossa/test/
